SELECT HD.FTBchCode,Pdt.FTPtyCode,ISNULL(PtyL.FTPtyName,'') AS FTPtyName, 
--ISNULL(FCXsdCostIn,0) AS FCXsdCostIn,
SUM(CASE WHEN HD.FNXshDocType = 1 THEN ISNULL(FCXsdCostIn,0)*ISNULL(FCXsdQtyAll,0) ELSE (ISNULL(FCXsdCostIn,0)*ISNULL(FCXsdQtyAll,0))*-1 END) AS FCXsdCostInTotal,
SUM(CASE WHEN HD.FNXshDocType = 1 THEN ISNULL(FCXsdNetAfHD,0) ELSE ISNULL(FCXsdNetAfHD,0)*-1 END) AS FCXsdNetAfHD
FROM TPSTSalDT DT WITH (NOLOCK) 
INNER JOIN TPSTSalHD HD WITH (NOLOCK) ON DT.FTBchCode = HD.FTBchCode AND DT.FTXshDocNo = HD.FTXshDocNo
LEFT JOIN TCNMPdt Pdt WITH (NOLOCK) ON DT.FTPdtCode = Pdt.FTPdtCode
LEFT JOIN TCNMPdtType_L PtyL WITH (NOLOCK) ON Pdt.FTPtyCode = PtyL.FTPtyCode AND PtyL.FNLngID = 1
GROUP BY HD.FTBchCode,Pdt.FTPtyCode,ISNULL(PtyL.FTPtyName,'')--,ISNULL(FCXsdCostIn,0) 

SELECT * FROM TPSTSalDT
SELECT * FROM TPSTSalHD
SELECT * FROM TCNMPdt
SELECT * FROM TCNMPdtType_L

SELECT * FROM TCNTPdtStkCrd
SELECT * FROM TCNTPdtStkCrdBch
SELECT * FROM TCNTPdtStkCrdMe
SELECT * FROM TCNTPdtStkCrdMEBch






