SET LANGUAGE Thai
SELECT DATENAME(month,GETDATE()) + ' ' + CONVERT(VARCHAR(4),CASE WHEN YEAR(GETDATE()) - 543 < 1800 THEN  YEAR(GETDATE()) + 543 ELSE  YEAR(GETDATE()) END) AS FTXshMonthTH
--SELECT GETDATE() 'Today', CASE WHEN YEAR(GETDATE()) - 543 < 1800 THEN  YEAR(GETDATE()) + 543 ELSE  YEAR(GETDATE()) END
SELECT FORMAT( GETDATE(), 'dd/MMM/yyyy', 'en-US' ) AS 'Date'  
SELECT FORMAT( GETDATE(), 'MMMM yyyy', 'Th' ) AS 'Date'  
SELECT FORMAT(FDXshDocDate, 'MM', 'en-US' ) AS 'Month'  FROM TPSTSalHD
SELECT FORMAT( FDXshDocDate, 'yyyy', 'en-US' ) AS 'Year' FROM TPSTSalHD  


SET LANGUAGE English
SELECT DATENAME(mm,GETDATE())  + ' ' +  CONVERT(VARCHAR(4),YEAR(GETDATE()))  AS FTXshMonthEN
SELECT * FROM TRPTPSTaxHDDateTmp

--SELECT FTXshDocVatFull,* FROM TPSTSalHD WHERE FTXshDocNo ='S2200001000020000018'
--SELECT * FROM TPSTSalHDCst WHERE FTXshDocNo ='S2200001000020000018'

SELECT HDL.FTBchCode,CONVERT(VARCHAR(10),FDXshDocDate,121) AS FDXshDocDate,
MIN(FTXshDocNo) + '-' + Max(FTXshDocNo) AS FTXshDocLegth
, ISNULL(HDL.FTXshDocVatFull,'') AS FTXshDocVatFull , 
CASE WHEN ISNULL(HDL.FTXshDocVatFull,'') = '' THEN '1' ELSE '2' END AS FTXshGenTax --'2'
FROM TPSTSalHD HDL
LEFT JOIN 
	(
	  SELECT FTBchCode,FTXshDocVatFull,FTXshDocVatFull + '(' + FTXshDocNo + ')' FROM TPSTSalHD WHERE ISNULL(FTXshDocVatFull,'') <> ''
	) HDFull ON HDL.FTBchCode = HDFull.FTBchCode AND HDL.FTXshDocVatFull = HDFull.FTXshDocVatFull
GROUP BY HDL.FTBchCode,CONVERT(VARCHAR(10),FDXshDocDate,121),ISNULL(HDL.FTXshDocVatFull,''),FNXshDocType


--SELECT *  FROM TPSTSalHD 

--SELECT *  FROM TPSTSalHDCst 
SELECT *  FROM TCNMBranch
SELECT *  FROM TCNMShop

--SELECT * FROM TPSTTaxHD WHERE FTXshDocNo = 'S22000070000002'
--SELECT * FROM TPSTTaxHDCst WHERE FTXshDocNo = 'S22000010000002'
FTXshAddrTax

32.7103
3600100112091